-- Generated by WezTerm Configurator. Do not edit by hand; changes are overwritten on save.
-- [state:v1:H4sIAAAAAAAA/4RVW2/buBL+K8bkoQnAJnJbN6necnF6cpC0ge2iwEkCnhE1sllTpJaiYruu/vtiKNu57G7XejA5HM7t+2a4hkfytXYW0r6AgH5KQboaUjDaNksQ8IimoRrSNWSo5lPvGptDercGDAHVrCQb+PAWPRqDS0iTw34rwFWodFjx9pOA2jVeEet99pjrzR3neYUhul/DtbaEHtK7tx8GD62AylNNAVL4jr6Etm0fBChDaCUtdZDK5RzXXSL67xM+csZ5WasZlQQpnGEo0cJLeczjZtUbb7TWUDhP26RgrygKaNvNnaiMttaQ3sFeEn8gYC8/3q4GBRZb2XaVJCfH+TGvWIJFJ8OiW2WKP3gQoG1OS8rZR/8j+8bi5DhJoBXwR6PVXNZkSAVpMCMjiykrntpan3NonJ9BNWftgJnMuG5rQBX0I8mAWcRrKtVGee9d9i758A4EFM+EKuGPKytANb52XmZG27kkrEnqCMp5k2l1Rj81+VjrRCSHgxPRZ4ByKrAxQaoFF+9o5ko6WmA+wxk8HU4bLeuAPjSVRD9lxCDuuQh5pWW2krXyRNHdxe3bPqSfPrYCyGJmiM+cMV2GwTckgJakZO5K1LaOTCz0sqkghaKxism0r8r84N72ep5C421Plfm9JZuDgFhNSOHCqTl5EGAxsiXv9kyxwnXs7P7ZPJbarCCF/1I48+y1d+OsAwEL0tMZM/TMmRxa8Uz3iwuuF7HqDUv3Q0PLFWOb0jeGNoH/o6srV9PjHJ/7GDA5YnzPGBtcicExDbQNZOvYcptwNrnIWv8kSPvvDwcCCk8UVhWjG8hXngJ5uRsB8IEpPKcVU8h03eKJ78sKLXVtr7b9epr/aOpwi5bG0cMdXFMRoOPGnDgQFpx67xZd+nNa1a+MjCtc2AkTFs4b78lGgxcRXdjZCSCgdDnPpfPJ6PrX+D9Xl5NY8H8PZ/AUzuzJzPXw9GI4emECJm46NXTZGDPuCLm9d9nvv3J205igKxPdjCNDJ+7MheBKEGs4d9XqxuVMrHPjatplDyksX6byyu64MjrmwJtce9rGNoosENCBuYZb8iqO0fdJ7N/OePVb49cNQgoL+hnIl4edXCo0hif7/q57FtrmbiF6DPlBj2x+8ASEfu3gQYAhzCnOn04HX+kICLok1wRZamN0TcpZPu0nSdIKKLV91uRytuV7cjhQZEw01tQkM21zbacvCQRXVnkeV5fOhoi7ADRhN1GgQFOzkB43j86FW8RiZE0IXVm+z4jMtwpSfrfq4AnnvG7/mmkXJldLGm25PwZJkgjoRjVXc+F8LjNuTvRci959uLfru/Zh/+Ae3vyfAaQgyT5q7yy/nfIRvd4122Q4upG3o6+fR6c3T1Bx+TtQ5NMbLHWJU2bYUSiro2x6WNkp/J3es5f4ZLBTyEk5H59eznByNbke/hoNx1f/G/66+jIZfh6dToYX8uzbZPL1y5gD8LjgCGerinx8JDZjbMen7cB/pbEf2aOaOrhSmhcMdHb/TVPlGOhtHTA09RvR+y0L/wwAAP//yXBSJq4IAAA=]
-- Target platform: linux
local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()
local function with_foreground(style, color) style.foreground = color return style end
config.default_cwd = '/home/wadhah'
config.default_gui_startup_args = { 'start' }
config.set_environment_variables = { TERM_PROGRAM = 'wezterm' }
config.clean_exit_codes = { 0, 130 }
config.font = wezterm.font_with_fallback({ { family = 'JetBrains Mono', weight = 'Bold' }, { family = 'Noto Color Emoji' } })
config.font_size = 13.5
config.font_rules = {
  { intensity = 'Bold', font = with_foreground(wezterm.font_with_fallback({ { family = 'Iosevka', weight = 500 } }), 'tomato') },
}
config.dpi_by_screen = { ['DP-1'] = 96 }
config.freetype_interpreter_version = 40
config.color_scheme = 'Batman'
config.colors = {
  ansi = { '#000000', '#d70000', '#5faf00', '#d7af00', '#0087d7', '#af00af', '#00afaf', '#bcbcbc' },
  indexed = { [16] = '#af8700' },
  tab_bar = { active_tab = { bg_color = '#2b2042', fg_color = '#c0c0c0' } },
  quick_select_label_fg = { AnsiColor = 'Black' },
}
config.color_schemes = {
  ['My Scheme'] = { foreground = '#fff' },
}
config.window_decorations = 'TITLE|RESIZE|INTEGRATED_BUTTONS'
config.window_background_opacity = 0.85
config.window_background_image = '/tmp/bg.png'
config.background = {
  { source = { Gradient = { orientation = { Linear = { -45 } }, preset = 'Warm' } }, attachment = { Parallax = 0.1 }, opacity = 0.9 },
}
config.cursor_blink_ease_in = { CubicBezier = { 0, 0, 0.58, 1 } }
config.scrollback_lines = 5000
config.enable_scroll_bar = true
config.min_scroll_bar_height = '0.5cell'
config.keys = {
  { key = 't', mods = 'CTRL|SHIFT', action = act.SpawnTab('CurrentPaneDomain') },
  { key = 'h', mods = 'LEADER', action = act.AdjustPaneSize({ 'Left', 5 }) },
  { key = 'F11', action = act.ToggleFullScreen },
  { key = 'x', mods = 'CTRL', action = act.Multiple({ act.ScrollToBottom, act.CopyMode('Close') }) },
  { key = 'p', mods = 'CTRL', action = act.SplitPane({ direction = 'Right', size = { Percent = 30 } }) },
  { key = 'i', mods = 'CTRL', action = wezterm.action_callback(function(window, pane) end) },
}
config.key_tables = {
  resize_pane = { { key = 'LeftArrow', action = act.AdjustPaneSize({ 'Left', 1 }) } },
}
config.leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 1000 }
config.mouse_bindings = {
  { event = { Down = { streak = 1, button = { WheelUp = 1 } } }, mods = 'CTRL', alt_screen = false, action = act.IncreaseFontSize },
}
config.selection_word_boundary = ' \t\n{[}]()"\'`'
config.hyperlink_rules = wezterm.default_hyperlink_rules()
config.exec_domains = {
  wezterm.exec_domain('docker', function(cmd)
  return cmd
end, 'Docker'),
}

-- Custom Lua
do
wezterm.on('update-status', function(window, pane) end)
end

return config
