-- Generated by WezTerm Configurator. Do not edit by hand; changes are overwritten on save.
-- Target platform: linux
local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()
local function with_foreground(style, color) style.foreground = color return style end
config.default_cwd = '/home/wadhah'
config.default_gui_startup_args = { 'start' }
config.set_environment_variables = { TERM_PROGRAM = 'wezterm' }
config.clean_exit_codes = { 0, 130 }
config.font = wezterm.font_with_fallback({ { family = 'JetBrains Mono', weight = 'Bold' }, { family = 'Noto Color Emoji' } })
config.font_size = 13.5
config.font_rules = {
  { intensity = 'Bold', font = with_foreground(wezterm.font_with_fallback({ { family = 'Iosevka', weight = 500 } }), 'tomato') },
}
config.dpi_by_screen = { ['DP-1'] = 96 }
config.freetype_interpreter_version = 40
config.color_scheme = 'Batman'
config.colors = {
  ansi = { '#000000', '#d70000', '#5faf00', '#d7af00', '#0087d7', '#af00af', '#00afaf', '#bcbcbc' },
  indexed = { [16] = '#af8700' },
  tab_bar = { active_tab = { bg_color = '#2b2042', fg_color = '#c0c0c0' } },
  quick_select_label_fg = { AnsiColor = 'Black' },
}
config.color_schemes = {
  ['My Scheme'] = { foreground = '#fff' },
}
config.window_decorations = 'TITLE|RESIZE|INTEGRATED_BUTTONS'
config.window_background_opacity = 0.85
config.window_background_image = '/tmp/bg.png'
config.background = {
  { source = { Gradient = { orientation = { Linear = { -45 } }, preset = 'Warm' } }, attachment = { Parallax = 0.1 }, opacity = 0.9 },
}
config.cursor_blink_ease_in = { CubicBezier = { 0, 0, 0.58, 1 } }
config.scrollback_lines = 5000
config.enable_scroll_bar = true
config.min_scroll_bar_height = '0.5cell'
config.keys = {
  { key = 't', mods = 'CTRL|SHIFT', action = act.SpawnTab('CurrentPaneDomain') },
  { key = 'h', mods = 'LEADER', action = act.AdjustPaneSize({ 'Left', 5 }) },
  { key = 'F11', action = act.ToggleFullScreen },
  { key = 'x', mods = 'CTRL', action = act.Multiple({ act.ScrollToBottom, act.CopyMode('Close') }) },
  { key = 'p', mods = 'CTRL', action = act.SplitPane({ direction = 'Right', size = { Percent = 30 } }) },
  { key = 'i', mods = 'CTRL', action = wezterm.action_callback(function(window, pane) end) },
}
config.key_tables = {
  resize_pane = { { key = 'LeftArrow', action = act.AdjustPaneSize({ 'Left', 1 }) } },
}
config.leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 1000 }
config.mouse_bindings = {
  { event = { Down = { streak = 1, button = { WheelUp = 1 } } }, mods = 'CTRL', alt_screen = false, action = act.IncreaseFontSize },
}
config.selection_word_boundary = ' \t\n{[}]()"\'`'
config.hyperlink_rules = wezterm.default_hyperlink_rules()
config.exec_domains = {
  wezterm.exec_domain('docker', function(cmd)
  return cmd
end, 'Docker'),
}

-- Custom Lua
wezterm.on('update-status', function(window, pane) end)

return config
