// Package state holds the app's persisted configuration state and resolves
// the active WezTerm config paths.
package state

import (
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
)

// Version is the current state-file schema version.
const Version = 1

// Marker is emitted as line 1 of every generated wezterm.lua.
const Marker = "-- Generated by WezTerm Configurator. Do not edit by hand; changes are overwritten on save."

// State is the app's JSON state, mirroring the values that will be emitted
// into wezterm.lua.
type State struct {
	Version   int               `json:"version"`   // 1
	TargetOS  string            `json:"target_os"` // "linux"|"windows"|"macos"
	Values    map[string]any    `json:"values"`    // option → JSON value in the Lua-mirroring shape
	Raw       map[string]string `json:"raw"`       // option → verbatim Lua expression; wins over Values
	CustomLua string            `json:"custom_lua"`
}

// New returns an empty state for the given target OS.
func New(targetOS string) *State {
	return &State{
		Version:  Version,
		TargetOS: targetOS,
		Values:   map[string]any{},
		Raw:      map[string]string{},
	}
}

// RuntimeTarget maps runtime.GOOS to a target name.
func RuntimeTarget() string {
	switch runtime.GOOS {
	case "darwin":
		return "macos"
	case "windows":
		return "windows"
	default:
		return "linux"
	}
}

// Load reads the state file; a missing file yields a fresh runtime-target
// state with no error.
func Load(path string) (*State, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return New(RuntimeTarget()), nil
		}
		return nil, err
	}
	var s State
	if err := json.Unmarshal(b, &s); err != nil {
		return nil, err
	}
	if s.Values == nil {
		s.Values = map[string]any{}
	}
	if s.Raw == nil {
		s.Raw = map[string]string{}
	}
	if s.Version == 0 {
		s.Version = Version
	}
	if s.TargetOS == "" {
		s.TargetOS = RuntimeTarget()
	}
	return &s, nil
}

// Save writes the state atomically (tmp file + rename).
func (s *State) Save(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, b, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// Owned reports whether path exists and starts with the generator Marker.
func Owned(path string) (exists, owned bool, err error) {
	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, false, nil
		}
		return false, false, err
	}
	defer f.Close()
	buf := make([]byte, len(Marker))
	n, err := f.Read(buf)
	if err != nil && n == 0 {
		return true, false, nil // empty file: exists, not owned
	}
	return true, string(buf[:n]) == Marker, nil
}

// BackupUnowned copies path to path.bak-<timestamp> and returns the copy path.
func BackupUnowned(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	backup := path + ".bak-" + timeNow().Format("20060102-150405")
	if err := os.WriteFile(backup, b, 0o644); err != nil {
		return "", err
	}
	return backup, nil
}
