package catalog

// optionDocs holds the per-option help text from the option matrix;
// wired into opt() so the data files stay readable.
var optionDocs = map[string]string{
	"adjust_window_size_when_changing_font_size":  "When true, changing font size resizes the window; when false it changes terminal rows and columns instead.",
	"allow_download_protocols":                    "Allow escape-sequence protocols that download files (e.g. iTerm2 file transfer).",
	"allow_square_glyphs_to_overflow_width":       "Controls when wide square symbol glyphs may overflow their cell width: never, always, or only when followed by a space.",
	"allow_win32_input_mode":                      "Honor the ConPTY escape sequence that switches to the proprietary win32 keyboard encoding for win32 console applications.",
	"alternate_buffer_wheel_scroll_speed":         "Number of arrow key presses generated per mouse wheel tick while an app uses the alternate screen buffer without mouse reporting.",
	"animation_fps":                               "Maximum frame rate for easing effects such as blinking cursor, blinking text and visual bell; higher is smoother but uses more GPU.",
	"anti_alias_custom_block_glyphs":              "Whether custom block glyphs are anti-aliased; smoother lines but can look less crisp at small font sizes.",
	"audible_bell":                                "Sound played when the BEL sequence rings the bell: system beep or alert sound, or no sound at all.",
	"automatically_reload_config":                 "Watch the config file and reload it automatically when it changes; false requires a manual reload key binding.",
	"background":                                  "Composes image, gradient or color layers for the pane background, with per-layer opacity, alignment, tiling, HSB and parallax scrolling.",
	"bidi_direction":                              "Paragraph direction hint used when bidi_enabled is true.",
	"bidi_enabled":                                "Enable bidirectional (right-to-left) text handling.",
	"bold_brightens_ansi_colors":                  "Whether bold text shifts palette colors 0-7 to bright variants; BrightOnly brightens color without using a bold font.",
	"bypass_mouse_reporting_modifiers":            "Modifier key(s) that bypass application mouse reporting, routing clicks through wezterm mouse assignments instead.",
	"canonicalize_pasted_newlines":                "Normalizes newlines in pasted text to LF, CR, CRLF or leaves them unchanged; effective value is None under bracketed paste mode.",
	"cell_width":                                  "Scales computed terminal cell width to adjust horizontal spacing; does not stretch glyphs, and may disturb ligatures.",
	"cell_widths":                                 "Overrides per-character cell widths with first/last/width ranges; takes priority over treat_east_asian_ambiguous_width_as_wide.",
	"char_select_bg_color":                        "Background color of the character selection palette (CharSelect).",
	"char_select_fg_color":                        "Text color of the character selection palette (CharSelect).",
	"char_select_font":                            "Font used by the character selection palette; supports fallbacks and options like window_frame.font.",
	"char_select_font_size":                       "Font size in points used by the character selection palette (CharSelect).",
	"check_for_updates":                           "Periodically check GitHub for a new stable wezterm release and show an update notice; no data collected, nothing auto-downloaded.",
	"check_for_updates_interval_seconds":          "Seconds between update checks (default 24 hours).",
	"clean_exit_codes":                            "Exit codes treated as a clean exit by exit_behavior; 0 is always clean and can be omitted.",
	"color_scheme":                                "Name of a built-in or user-defined (color_schemes) color scheme; colors below override individual entries of it.",
	"color_scheme_dirs":                           "Extra directories to search for color scheme TOML files, in addition to <config dir>/colors.",
	"color_schemes":                               "Defines named color schemes in your configuration for easy switching.",
	"colors":                                      "Specifies the terminal color palette; see Colors and Appearance documentation for full field list.",
	"command_palette_bg_color":                    "Background color of the command palette.",
	"command_palette_fg_color":                    "Text color of the command palette.",
	"command_palette_font":                        "Font used by the command palette; supports fallbacks and options like window_frame.font.",
	"command_palette_font_size":                   "Font size in points used by the command palette.",
	"command_palette_line_height":                 "Scales the computed line height of command palette rows; values like 1.2 increase vertical spacing.",
	"command_palette_rows":                        "Number of rows displayed by the command palette; unset or nil uses a display-based default.",
	"cursor_blink_ease_in":                        "Easing function for the cursor color when fading in during blinking.",
	"cursor_blink_ease_out":                       "Easing function for the cursor color when fading out during blinking.",
	"cursor_blink_rate":                           "How often a blinking cursor toggles between visible and invisible, in milliseconds; 0 disables blinking. Value is approximate.",
	"cursor_thickness":                            "Overrides cursor line thickness; accepts pixels, points (DPI-scaled), percent of underline thickness or fraction of cell height.",
	"custom_block_glyphs":                         "Compute built-in box-drawing, block, braille, powerline and similar glyphs instead of using font-provided ones.",
	"daemon_options":                              "Configures mux server daemon file locations: pid and lock file plus stdout and stderr logs. Rarely needs changing.",
	"debug_key_events":                            "Logs every key event at INFO level to stderr for debugging keyboard decoding; launch wezterm from a terminal to see the log.",
	"default_cursor_style":                        "Default cursor style used when not overridden by escape sequences; blinking styles add graphics load.",
	"default_cwd":                                 "Default current working directory for the initial window; later panes prefer OSC 7 or resolved process cwd.",
	"default_domain":                              "Default multiplexing domain for the GUI, e.g. a WSL distribution name instead of the built-in local domain.",
	"default_gui_startup_args":                    "Default subcommand used when launching wezterm without arguments; command line arguments always take precedence.",
	"default_mux_server_domain":                   "Default multiplexing domain for the standalone mux server; client domains such as TLS, SSH or Unix are prohibited.",
	"default_prog":                                "Program and arguments run in new panes when none is specified, instead of the user's shell.",
	"default_ssh_auth_sock":                       "Replaces the SSH_AUTH_SOCK environment value and the auth socket registered with the mux server.",
	"default_workspace":                           "Name of the default workspace.",
	"detect_password_input":                       "Shows a lock cursor when a local unix PTY has echo disabled and canonical input enabled, hinting at password entry; does not work through tmux or ssh.",
	"disable_default_key_bindings":                "Disable every default key assignment so only the bindings you define apply (keep a ShowDebugOverlay binding!).",
	"disable_default_mouse_bindings":              "When true, wezterm's default mouse assignments are not used, letting you fully define mouse behavior.",
	"disable_default_quick_select_patterns":       "When true, omits built-in quick select patterns so quick_select_patterns defines the complete set.",
	"display_pixel_geometry":                      "Subpixel anti-aliasing output order matching your display's pixel geometry; use BGR for BGR-ordered panels.",
	"dpi":                                         "Overrides the detected display DPI when text is blurry or too small, especially 4K displays on X11 or Wayland.",
	"dpi_by_screen":                               "Per-screen DPI overrides keyed by screen name as reported by wezterm.gui.screens(); overrides dpi for that screen.",
	"enable_checksum_rectangular_area":            "Respond to DECRQCRA checksum requests (off by default: lets programs read screen contents).",
	"enable_csi_u_key_encoding":                   "Enables the fixterms CSI-u keyboard encoding; not recommended, changes key behavior incompatibly, and allow_win32_input_mode takes precedence.",
	"enable_kitty_graphics":                       "Honor the kitty graphics protocol for inline images.",
	"enable_kitty_keyboard":                       "Honor kitty keyboard protocol escape sequences that modify the keyboard encoding.",
	"enable_scroll_bar":                           "Show a scrollbar in the right window padding; if right padding is 0 it grows to one cell width.",
	"enable_tab_bar":                              "Controls whether the tab bar is shown.",
	"enable_title_reporting":                      "Respond to escape sequences that ask to read back the window title (off by default: lets programs read the title).",
	"enable_wayland":                              "Use a Wayland connection for the GUI frontend; false falls back to X11. Only relevant on X11/Wayland systems.",
	"enable_zwlr_output_manager":                  "Use the zwlr_output_manager Wayland protocol to enumerate outputs (monitors).",
	"enq_answerback":                              "String sent in response to the ENQ (0x05) control character.",
	"exec_domains":                                "Custom multiplexer domains built with wezterm.exec_domain: a name plus a Lua fixup function that rewrites the command about to be spawned (e.g. to wrap it in a container).",
	"exit_behavior":                               "What happens to a pane when its shell exits: close it, hold it open, or close only after a clean exit status.",
	"exit_behavior_messaging":                     "Controls the message shown when a pane's process ends while exit_behavior keeps the pane open, from verbose explanation to nothing.",
	"experimental_pixel_positioning":              "Experimental: place glyphs at the fractional pixel positions produced by shaping instead of snapping them to cell boundaries.",
	"font":                                        "Default font; can specify fallbacks and options, described in the Fonts documentation.",
	"font_colr_rasterizer":                        "Rasterizer used for COLR (colored vector) glyphs such as color emoji.",
	"font_dirs":                                   "Extra directories scanned for fonts, searched after the system font locator; combine with font_locator ConfigDirsOnly to use only these.",
	"font_locator":                                "Method for locating system fonts; ConfigDirsOnly restricts lookup to font_dirs, disabling system fonts.",
	"font_rasterizer":                             "Font rendering implementation; FreeType is the only available choice.",
	"font_rules":                                  "Rules deciding which font renders bold, italic, dim or underlined text; defaults are usually sufficient.",
	"font_shaper":                                 "Text shaping engine mapping text to glyphs (kerning, ligatures, emoji); keep Harfbuzz. Allsorts shaper removed in 20211204-082213-a66c61ee9. _(Allsorts removed upstream; keep Harfbuzz)_",
	"font_size":                                   "Font size in points; fractional values like 13.3 are allowed.",
	"force_reverse_video_cursor":                  "When true, forces cursor to reverse-video colors from foreground and background, overriding scheme cursor colors; escape sequences still take precedence since 20220319-142410-0fcdea07.",
	"foreground_text_hsb":                         "Hue, saturation, brightness multipliers applied to text colors; 1.0 preserves, 0.5 halves, 2.0 doubles.",
	"freetype_interpreter_version":                "FreeType interpreter version controlling subpixel hinting behavior; 35, 38 or 40.",
	"freetype_load_flags":                         "Advanced FreeType load flags combined with \\|, e.g. NO_HINTING\\|MONOCHROME.",
	"freetype_load_target":                        "Freetype hinting and rendering mode: Normal, Light, Mono, or LCD subpixel variants HorizontalLcd and VerticalLcd.",
	"freetype_pcf_long_family_names":              "Controls the FreeType PCF long family names property; true prefixes foundry names such as xos4 Terminus; only useful with fontconfig and PCF fonts.",
	"freetype_render_target":                      "Freetype rendering mode, separate from hinting; defaults to freetype_load_target, override for fine control.",
	"front_end":                                   "Rendering backend: GPU OpenGL, CPU Software, or GPU WebGpu using Metal, Vulkan or DirectX 12.",
	"glyph_cache_image_cache_size":                "Entries kept in the glyph image cache.",
	"harfbuzz_features":                           "List of OpenType font features applied during Harfbuzz shaping, e.g. calt=0 disables contextual alternates. Only used when font_shaper is Harfbuzz.",
	"hide_mouse_cursor_when_typing":               "Hides the mouse cursor while typing when it hovers over the window. Enabled by default.",
	"hide_tab_bar_if_only_one_tab":                "Hides the tab bar while only one tab exists; the bar reappears when a second tab is created.",
	"hyperlink_rules":                             "Rules turning terminal text into clickable links; each rule has regex, format, and optional highlight capture group.",
	"ignore_svg_fonts":                            "Ignore SVG glyph tables embedded in fonts (use bitmap/outline glyphs instead).",
	"ime_preedit_rendering":                       "Chooses whether WezTerm (Builtin) or the system (System) draws IME preedit text; no effect on macOS. Restart required after changing.",
	"inactive_pane_hsb":                           "Hue/saturation/brightness multipliers applied to inactive panes to dim them.",
	"initial_cols":                                "Width of newly created windows, measured in terminal character cells.",
	"initial_rows":                                "Height of newly created windows, measured in terminal character cells.",
	"integrated_title_button_alignment":           "Places integrated window management buttons on the left or right side of the tab bar.",
	"integrated_title_button_color":               "Color of integrated title bar buttons; Auto derives it from the tab bar colors, or set a named color.",
	"integrated_title_button_style":               "Visual style of integrated title bar buttons: Windows, Gnome, or MacOsNative; default is MacOsNative on macOS, Windows elsewhere.",
	"integrated_title_buttons":                    "Ordered list of integrated window buttons to show: Hide, Maximize, Close. Omit entries to remove buttons.",
	"kde_window_background_blur":                  "Deprecated. Enables KDE Wayland background blur together with window_background_opacity; use wayland_window_background_blur instead. **DEPRECATED:** this option has been replaced with `wayland_window_background_blur` and will be removed in a future release",
	"key_map_preference":                          "Treats keys without a phys: or mapped: prefix as Physical or Mapped; default key assignments respect it too.",
	"key_tables":                                  "Defines named key tables activated with ActivateKeyTable for modal keyboard customization, such as resize or activate pane modes.",
	"keys":                                        "Custom key assignments: each entry maps a key plus modifiers to an action (see the Action editor).",
	"launch_menu":                                 "Adds custom entries to the launcher menu; each entry is a SpawnCommand with label, args, cwd, environment, and domain.",
	"launcher_alphabet":                           "Characters used for one or two key press shortcuts choosing launcher entries; default omits j and k for movement.",
	"leader":                                      "Leader key (tmux-style prefix): after pressing it, bindings whose mods include LEADER are active for timeout_milliseconds.",
	"line_height":                                 "Multiplier scaling spacing between text rows; 1.2 increases vertical spacing twenty percent, 0.9 decreases it ten percent.",
	"line_quad_cache_size":                        "Entries kept in the line quad (render geometry) cache.",
	"line_state_cache_size":                       "Entries kept in the line state cache.",
	"line_to_ele_shape_cache_size":                "Entries kept in the line-to-element shape cache.",
	"log_unknown_escape_sequences":                "Logs warnings for escape sequences WezTerm does not understand; harmless and mainly useful for debugging.",
	"macos_forward_to_ime_modifier_mask":          "macOS only: modifiers that route key presses through the IME; SHIFT by default, SHIFT\\\\|CTRL helps Japanese IMEs but breaks some Ctrl combos.",
	"macos_fullscreen_extend_behind_notch":        "macOS only: full screen window extends behind the display notch; requires native_macos_fullscreen_mode false and manual fullscreen toggle.",
	"macos_window_background_blur":                "macOS only: blur radius applied behind a translucent window when combined with window_background_opacity; 0 disables blur.",
	"max_fps":                                     "Upper limit on frames per second WezTerm draws; ignored on Wayland, which uses compositor timing instead.",
	"min_scroll_bar_height":                       "Minimum size of the scroll bar thumb; number of pixels or string with px, pt, cell, or percent unit.",
	"mouse_bindings":                              "Custom mouse assignments: each maps a button event (Down/Up/Drag, click streak, modifiers) to an action.",
	"mouse_wheel_scrolls_tabs":                    "Vertical mouse wheel switches tabs when hovering the tab bar; enabled by default.",
	"mux_enable_ssh_agent":                        "Points SSH_AUTH_SOCK for local panes at a symlink tracking the most recently active multiplexer client.",
	"mux_env_remove":                              "Environment variables removed from the multiplexer server environment before spawning sessions, avoiding misleading values.",
	"mux_output_parser_buffer_size":               "Buffer size in bytes used by the multiplexer when parsing pane output.",
	"mux_output_parser_coalesce_delay_ms":         "Milliseconds to wait after reading output so fragmented writes are coalesced (reduces tearing).",
	"native_macos_fullscreen_mode":                "macOS only: use native full screen with a separate Space and animation instead of instant borderless fullscreen.",
	"normalize_output_to_unicode_nfc":             "Normalizes terminal output to Unicode NFC, which can fix Korean or mixed normalization glitches but may introduce others.",
	"notification_handling":                       "Controls toast notifications from escape sequences: always show, never show, or suppress when from the focused pane, tab, or window.",
	"palette_max_key_assigments_for_action":       "Maximum number of key assignments listed per action in the command palette.",
	"pane_focus_follows_mouse":                    "Activates a pane when the mouse moves over it; otherwise a click is required to focus a pane.",
	"pane_select_bg_color":                        "Background color of PaneSelect labels.",
	"pane_select_fg_color":                        "Text color of PaneSelect labels.",
	"pane_select_font":                            "Font used during pane selection mode; defaults to the window_frame font.",
	"pane_select_font_size":                       "Font size in points of the labels drawn by PaneSelect.",
	"periodic_stat_logging":                       "If non-zero, log internal statistics every N seconds (minimum period 10 s).",
	"prefer_egl":                                  "Whether WezTerm uses EGL for GPU access; true uses ANGLE on Windows and MetalANGLE on macOS when installed.",
	"prefer_to_spawn_tabs":                        "Launching wezterm while a GUI instance runs opens a new tab instead of a new window.",
	"quick_select_alphabet":                       "Alphabet generating labels for quick select mode matches; default suits qwerty; page suggests qwertz, azerty, dvorak, colemak alternatives.",
	"quick_select_patterns":                       "Extra regular expressions matched in quick select mode; use non-capturing groups so the combined alternation works.",
	"quick_select_remove_styling":                 "Strips colors and styling from the pane before quick select matching and highlighting.",
	"quit_when_all_windows_are_closed":            "Terminates WezTerm when the last window closes; set false to keep it running.",
	"quote_dropped_files":                         "How dragged file names are quoted: None, SpacesOnly, Posix, Windows, or WindowsAlwaysQuoted; default is platform dependent.",
	"ratelimit_mux_line_prefetches_per_second":    "Rate limit for speculative line prefetches made by the multiplexer client.",
	"reverse_video_cursor_min_contrast":           "Minimum contrast ratio for the reverse video cursor; below it the default cursor foreground and background colors are used.",
	"scroll_to_bottom_on_input":                   "Automatically scrolls the viewport to the bottom of scrollback when there is terminal input.",
	"scrollback_lines":                            "Number of scrollback lines retained per pane.",
	"search_font_dirs_for_fallback":               "Also search font_dirs when resolving fallback fonts for glyphs missing from the primary font.",
	"selection_word_boundary":                     "Characters treated as word boundaries for mouse word selection and extend-selection actions.",
	"send_composed_key_when_left_alt_is_pressed":  "Treat Left Alt as a compose/Option key producing composed characters instead of an Alt-modified key (mainly macOS).",
	"send_composed_key_when_right_alt_is_pressed": "Treat Right Alt as a compose/Option key producing composed characters instead of an Alt-modified key (mainly macOS).",
	"serial_ports":                                "Defines serial port domains with name, port device path, and baud rate for wezterm serial connections.",
	"set_environment_variables":                   "Environment variables set when spawning commands in the local domain; not applied to remote domains or already running programs.",
	"shape_cache_size":                            "Entries kept in the glyph shaping cache.",
	"show_close_tab_button_in_tabs":               "Shows the close button on tabs when the fancy tab bar is used.",
	"show_new_tab_button_in_tab_bar":              "Shows the new tab button; left click creates a tab, right click opens the launcher menu.",
	"show_tab_index_in_tab_bar":                   "Prefixes tab titles with their number, such as 1:; numbering start honors tab_and_split_indices_are_zero_based.",
	"show_tabs_in_tab_bar":                        "Shows tabs in the tab bar; disabling leaves only the left and right status areas.",
	"show_update_window":                          "Deprecated: previously showed a window when a new version was detected; no longer has any effect. **DEPRECATED:** this option no longer does anything and will be removed in a future release",
	"skip_close_confirmation_for_processes_named": "Process names considered stateless and safe to close without a confirmation prompt, such as shells and tmux.",
	"sort_fallback_fonts_by_coverage":             "Sort fallback fonts by how many codepoints they cover before trying them.",
	"ssh_backend":                                 "Selects the integrated ssh client implementation: LibSsh or Ssh2; LibSsh is the default with broader key and cryptography support.",
	"ssh_domains":                                 "Configures SSH multiplexing domains; when unset WezTerm derives defaults as if calling wezterm.default_ssh_domains.",
	"status_update_interval":                      "Milliseconds that must elapse between update-status and update-right-status event triggers.",
	"strikethrough_position":                      "Overrides strikethrough line position in pixels, points, percent of font metric, or cell height; defaults to the font metric.",
	"swallow_mouse_click_on_pane_focus":           "When true, clicking a pane only focuses it; when false the click also passes through to the application.",
	"swallow_mouse_click_on_window_focus":         "When true, clicking a window only focuses it; default is true on macOS, false on other systems.",
	"swap_backspace_and_delete":                   "Swaps Backspace and Delete key interpretation so each generates the other's code.",
	"switch_to_last_active_tab_when_closing_tab":  "After closing the active tab, activates the previously active tab instead of the tab to the left.",
	"tab_and_split_indices_are_zero_based":        "When true, show_tab_index_in_tab_bar uses zero-based indices; default false shows one-based.",
	"tab_bar_at_bottom":                           "Renders tab bar at bottom of the window instead of the top when true.",
	"tab_bar_style":                               "Styles tab edges, new-tab button, integrated window buttons; colors come from configured tab bar colors.",
	"tab_max_width":                               "Maximum tab width in retro tab mode; ignored when using fancy tab mode.",
	"term":                                        "TERM environment variable for spawned programs; wezterm terminfo adds styled underlines, italics, truecolor.",
	"text_background_opacity":                     "Opacity of the background color painted behind text cells; below 1.0 the window background shows through cells with a background color.",
	"text_blink_ease_in":                          "Easing for blinking text fading-in phase, background color to foreground color.",
	"text_blink_ease_out":                         "Easing for blinking text fading-out phase, foreground color to background color.",
	"text_blink_rapid_ease_in":                    "Easing for rapid-blinking text fading-in phase.",
	"text_blink_rapid_ease_out":                   "Easing for rapid-blinking text fading-out phase.",
	"text_blink_rate":                             "How often normal-speed blinking text transitions visible/invisible; approximate due to timer slop.",
	"text_blink_rate_rapid":                       "How often rapid-blinking text transitions visible/invisible; approximate due to timer slop.",
	"text_min_contrast_ratio":                     "Minimum foreground/background contrast ratio; foreground luminance adjusted to try to meet it.",
	"tiling_desktop_environments":                 "Names of tiling window-manager environments; used for adjust_window_size_when_changing_font_size default.",
	"tls_clients":                                 "Configures TLS multiplexing client domains; see multiplexing docs.",
	"tls_servers":                                 "Configures TLS multiplexing server domains; see multiplexing docs.",
	"treat_east_asian_ambiguous_width_as_wide":    "Treat ambiguous-width Unicode codepoints as two cells when true; single cell by default.",
	"treat_left_ctrlalt_as_altgr":                 "Treat left Ctrl-Alt as AltGr (VNC workaround); separate Ctrl and Alt bindings stop triggering.",
	"ui_key_cap_rendering":                        "Controls keyboard shortcut rendering in the Command Palette.",
	"ulimit_nofile":                               "Minimum desired RLIMIT_NOFILE soft limit on Unix; raised to min(value, hard limit) at startup.",
	"ulimit_nproc":                                "Minimum desired RLIMIT_NPROC soft limit on Unix; raised to min(value, hard limit) at startup.",
	"underline_position":                          "Overrides underline position; offset from font baseline, often a small negative number like -2.",
	"underline_thickness":                         "Overrides underline thickness; also used for split pane dividers and custom glyph lines.",
	"unicode_version":                             "Unicode version used for width/presentation; runtime change via OSC 1337 UnicodeVersion push/pop.",
	"unix_domains":                                "Multiplexer domains over unix sockets for server and client; full fields in multiplexing docs.",
	"unzoom_on_switch_pane":                       "When false, ActivatePaneDirection does nothing while a pane is zoomed; true unzooms then switches.",
	"use_box_model_render":                        "Experimental box-model renderer for UI elements such as the tab bar.",
	"use_cap_height_to_scale_fallback_fonts":      "Uses cap-height metrics of base font to size secondary fonts (bold, italic) to visually match.",
	"use_dead_keys":                               "Enable dead-key composition (e.g. ` then e gives \u00e8); false sends the dead key immediately as a plain key.",
	"use_fancy_tab_bar":                           "True renders native-style tab bar with proportional fonts; false renders retro bar with terminal font.",
	"use_ime":                                     "Enables Input Method Editor for kanji and other text input; changing usually requires relaunch.",
	"use_resize_increments":                       "Snap window size to multiples of terminal cell size; padding accounted since 20240127-113634-bbcac864.",
	"visual_bell":                                 "Visual representation of BEL: flash pane background or cursor color; zero total durations disables.",
	"warn_about_missing_glyphs":                   "Shows configuration error window pointing to font docs when a glyph cannot be found.",
	"wayland_window_background_blur":              "Enables Wayland background blur protocol with window_background_opacity; compositors may need blur enabled explicitly.",
	"webgpu_force_fallback_adapter":               "Forces software CPU-based rendering backend; only applicable when front_end = \"WebGpu\".",
	"webgpu_power_preference":                     "Power preference when selecting a WebGpu GPU instance; only with front_end = \"WebGpu\".",
	"webgpu_preferred_adapter":                    "Selects a specific WebGpu adapter; obtain candidates from wezterm.gui.enumerate_gpus().",
	"win32_acrylic_accent_color":                  "Accent color for Acrylic composition effect on Windows builds earlier than 22621.",
	"win32_system_backdrop":                       "Windows backdrop effect behind translucent window; needs opacity below 1.0 (0 for Mica/Tabbed).",
	"window_background_gradient":                  "Generates window background image from gradient specification; overrides window_background_image.",
	"window_background_image":                     "Background image scaled to fit window; animated GIF/PNG animate while focused; ignored when gradient set.",
	"window_background_image_hsb":                 "HSV multipliers applied to window_background_image; 1.0 preserves, 0.5 halves, 2.0 doubles.",
	"window_background_opacity":                   "Window background alpha; also applies to background image and gradient layers; macOS disables shadow below 1.0.",
	"window_close_confirmation":                   "Prompts when the windowing environment closes the window; does not apply to CTRL-SHIFT-W or CMD-w.",
	"window_content_alignment":                    "Controls where the leftover gap goes when window size is not a multiple of cell size.",
	"window_decorations":                          "Title bar and resizable border flags; keep RESIZE; MACOS_FORCE_SQUARE_CORNERS incompatible with TITLE/INTEGRATED_BUTTONS.",
	"window_frame":                                "Window frame colors, optional border, tab bar font and size; some colors used by fancy tab bar.",
	"window_padding":                              "Padding between window border and terminal cells; with scrollbar enabled, right padding sets scrollbar width.",
	"wsl_domains":                                 "WSL multiplexing domains enabling panes/tabs that share working directory.",
	"xcursor_size":                                "Mouse cursor size in pixels for X11/Wayland.",
	"xcursor_theme":                               "Cursor theme name for X11/Wayland (e.g. Adwaita); overrides the desktop setting.",
	"xim_im_name":                                 "Explicit IME server name for X11 XIM when use_ime is true; overrides XMODIFIERS.",
}
