package catalog

var textRenderOptions = []Option{
	opt(Field{Name: "font_rasterizer", Kind: Enum, Enum: []string{"FreeType", "Harfbuzz"}, Default: "FreeType"}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "font_colr_rasterizer", Kind: Enum, Enum: []string{"FreeType", "Harfbuzz"}, Default: "Harfbuzz"}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "font_shaper", Kind: Enum, Enum: []string{"Harfbuzz", "Allsorts"}, Default: "Harfbuzz"}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "harfbuzz_features", Kind: StringList, Default: []any{"kern", "liga", "clig"}}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "freetype_load_target", Kind: Enum, Enum: []string{"Normal", "Light", "Mono", "HorizontalLcd", "VerticalLcd"}, Default: "Normal"}, "Text Rendering", "20210314-114017-04b7cedd", nil, nil, ""),
	opt(Field{Name: "freetype_render_target", Kind: Enum, Enum: []string{"Normal", "Light", "Mono", "HorizontalLcd", "VerticalLcd"}, DefaultNote: "= freetype_load_target"}, "Text Rendering", "20210502-130208-bff6815d", nil, nil, ""),
	opt(Field{Name: "freetype_load_flags", Kind: Flags, Enum: []string{"DEFAULT", "NO_HINTING", "NO_BITMAP", "FORCE_AUTOHINT", "MONOCHROME", "NO_AUTOHINT", "NO_SVG", "SVG_ONLY"}, EmptyToken: "DEFAULT", DefaultNote: "NO_HINTING when dpi >= 100, else DEFAULT"}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "freetype_interpreter_version", Kind: Enum, Enum: []string{"35", "38", "40"}}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "freetype_pcf_long_family_names", Kind: Bool, Default: false}, "Text Rendering", "20220624-141144-bd1b7c5d", []string{"Linux"}, nil, ""),
	opt(Field{Name: "display_pixel_geometry", Kind: Enum, Enum: []string{"RGB", "BGR"}, Default: "RGB"}, "Text Rendering", "20230408-112425-69ae8472", nil, nil, ""),
	opt(Field{Name: "allow_square_glyphs_to_overflow_width", Kind: Enum, Enum: []string{"WhenFollowedBySpace", "Always", "Never"}, Default: "WhenFollowedBySpace"}, "Text Rendering", "20210203-095643-70a364eb", nil, nil, ""),
	opt(Field{Name: "custom_block_glyphs", Kind: Bool, Default: true}, "Text Rendering", "20210314-114017-04b7cedd", nil, nil, ""),
	opt(Field{Name: "anti_alias_custom_block_glyphs", Kind: Bool, Default: true}, "Text Rendering", "20220405-091515-8a0072ad", nil, nil, ""),
	opt(Field{Name: "underline_position", Kind: Dimension, DefaultNote: "font metric"}, "Text Rendering", "20221119-145034-49b9839f", nil, nil, ""),
	opt(Field{Name: "underline_thickness", Kind: Dimension, DefaultNote: "font metric"}, "Text Rendering", "20221119-145034-49b9839f", nil, nil, ""),
	opt(Field{Name: "strikethrough_position", Kind: Dimension, DefaultNote: "font metric"}, "Text Rendering", "20221119-145034-49b9839f", nil, nil, ""),
	opt(Field{Name: "cursor_thickness", Kind: Dimension, DefaultNote: "= underline thickness"}, "Text Rendering", "20221119-145034-49b9839f", nil, nil, ""),
	opt(Field{Name: "unicode_version", Kind: Int, Min: ptr(0), Default: 9}, "Text Rendering", "20211204-082213-a66c61ee9", nil, nil, ""),
	opt(Field{Name: "treat_east_asian_ambiguous_width_as_wide", Kind: Bool, Default: false}, "Text Rendering", "20220624-141144-bd1b7c5d", nil, nil, ""),
	opt(Field{Name: "cell_widths", Kind: List, Fields: CellWidthFields}, "Text Rendering", "nightly", nil, nil, ""),
	opt(Field{Name: "normalize_output_to_unicode_nfc", Kind: Bool, Default: false}, "Text Rendering", "20221119-145034-49b9839f", nil, nil, ""),
	opt(Field{Name: "bidi_enabled", Kind: Bool, Default: false}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "bidi_direction", Kind: Enum, Enum: []string{"LeftToRight", "RightToLeft", "AutoLeftToRight", "AutoRightToLeft"}, Default: "LeftToRight"}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "experimental_pixel_positioning", Kind: Bool, Default: false}, "Text Rendering", "", nil, nil, ""),
	opt(Field{Name: "use_box_model_render", Kind: Bool, Default: false}, "Text Rendering", "", nil, nil, ""),
}
