package catalog

// valueDocs explains individual choices of Enum and Flags fields, shown by the
// "?" next to each choice in the UI. Keys are "field/Value" when the meaning
// depends on the field, otherwise just "Value" (shared by every field using
// that word). ValueDoc tries the specific key first.
var valueDocs = map[string]string{
	// ---- shared words
	"Clipboard":                    "The system clipboard (Ctrl+C / Ctrl+V).",
	"PrimarySelection":             "The X11/Wayland primary selection: filled by selecting text, pasted with middle-click.",
	"ClipboardAndPrimarySelection": "Both the system clipboard and the primary selection.",
	"Left":                         "Left.",
	"Right":                        "Right.",
	"Up":                           "Up.",
	"Down":                         "Down.",
	"Top":                          "Top.",
	"Middle":                       "Vertically centered.",
	"Center":                       "Centered.",
	"Bottom":                       "Bottom.",
	"Next":                         "The next pane in order.",
	"Prev":                         "The previous pane in order.",
	"None":                         "Off: nothing is applied.",
	"Normal":                       "Regular, unmodified.",
	"Linear":                       "Straight, even progression.",
	"Repeat":                       "Tile the image again and again.",
	"Mirror":                       "Tile the image, flipping every other copy.",
	"NoRepeat":                     "Draw the image once, no tiling.",
	"Cell":                         "Select single cells (characters), like a normal drag.",
	"Word":                         "Select whole words.",
	"Line":                         "Select whole lines.",
	"SemanticZone":                 "Select a semantic zone: a command's prompt, input or output, as marked by shell integration.",
	"Block":                        "Select a rectangular block of cells.",
	"Output":                       "Command output zone.",
	"Input":                        "Command input zone (what you typed).",
	"Prompt":                       "Prompt zone.",
	"SHIFT":                        "The Shift key.",
	"CTRL":                         "The Control key.",
	"ALT":                          "The Alt key (Option on macOS).",
	"SUPER":                        "The Super key (Windows key, Command on macOS).",
	"LEADER":                       "Active while the leader key has been pressed and is waiting for the next key.",
	"Any":                          "Match regardless of this state.",
	"true":                         "Only when true.",
	"false":                        "Only when false.",

	// ---- general & startup
	"exit_behavior/Close":                             "Close the pane when its process exits, whatever the exit code.",
	"exit_behavior/CloseOnCleanExit":                  "Close the pane only if the process exited cleanly (code 0 or one in clean_exit_codes); otherwise keep it open to show the error.",
	"exit_behavior/Hold":                              "Never close automatically; the pane stays until you close it.",
	"exit_behavior_messaging/Verbose":                 "Show the full explanation of why the process ended, including its exit status and how to close the pane.",
	"exit_behavior_messaging/Brief":                   "Show a short one-line note that the process ended.",
	"exit_behavior_messaging/Terse":                   "Show only the bare process status.",
	"exit_behavior_messaging/None":                    "Show nothing when the process ends.",
	"window_close_confirmation/AlwaysPrompt":          "Ask before closing a window, even when it is idle.",
	"window_close_confirmation/NeverPrompt":           "Close windows immediately without asking. Running programs are lost.",
	"ssh_backend/LibSsh":                              "Use libssh for SSH connections (the default).",
	"ssh_backend/Ssh2":                                "Use libssh2 for SSH connections.",
	"multiplexing/WezTerm":                            "WezTerm multiplexes the panes and tabs of this domain (the default).",
	"multiplexing/None":                               "No multiplexing: each pane is just a plain remote shell, useful if you run tmux on the remote.",
	"assume_shell/Unknown":                            "Don't assume the remote shell type.",
	"assume_shell/Posix":                              "Assume a POSIX shell so WezTerm can build cd/exec command lines that way.",
	"notification_handling/AlwaysShow":                "Always show toast notifications sent by programs.",
	"notification_handling/NeverShow":                 "Never show toast notifications.",
	"notification_handling/SuppressFromFocusedPane":   "Hide notifications from the pane you are looking at.",
	"notification_handling/SuppressFromFocusedTab":    "Hide notifications from any pane of the focused tab.",
	"notification_handling/SuppressFromFocusedWindow": "Hide notifications from any pane of the focused window.",
	"audible_bell/SystemBeep":                         "Play the operating system's beep on the terminal bell.",
	"audible_bell/Disabled":                           "Stay silent on the terminal bell.",

	// ---- fonts and text rendering
	"font_locator/FontConfig":              "Find fonts through fontconfig (default on Linux and BSD).",
	"font_locator/Gdi":                     "Use Windows GDI font enumeration (default on Windows).",
	"font_locator/CoreText":                "Use macOS CoreText (default on macOS).",
	"font_locator/ConfigDirsOnly":          "Only load fonts from font_dirs; installed system fonts are ignored.",
	"font_rasterizer/FreeType":             "Draw glyphs with FreeType (the default).",
	"font_rasterizer/Harfbuzz":             "Draw glyphs with HarfBuzz's own rasterizer.",
	"font_colr_rasterizer/FreeType":        "Draw COLR colour glyphs through FreeType.",
	"font_colr_rasterizer/Harfbuzz":        "Draw COLR colour glyphs with HarfBuzz's paint API.",
	"font_shaper/Harfbuzz":                 "Shape text with HarfBuzz: full OpenType support, ligatures (the default).",
	"font_shaper/Allsorts":                 "Shape text with the pure-Rust Allsorts library (experimental).",
	"freetype_load_target/Normal":          "Standard grayscale anti-aliasing with full hinting.",
	"freetype_load_target/Light":           "Lighter hinting that only snaps vertically; shapes stay closer to the design.",
	"freetype_load_target/Mono":            "1-bit black and white, no anti-aliasing.",
	"freetype_load_target/HorizontalLcd":   "Hint for sub-pixel rendering on horizontal RGB LCD panels.",
	"freetype_load_target/VerticalLcd":     "Hint for sub-pixel rendering on vertical-stripe LCD panels.",
	"freetype_render_target/Normal":        "Render with standard grayscale anti-aliasing.",
	"freetype_render_target/Light":         "Render with light grayscale anti-aliasing.",
	"freetype_render_target/Mono":          "Render 1-bit black and white glyphs.",
	"freetype_render_target/HorizontalLcd": "Render sub-pixel glyphs for horizontal RGB LCD panels.",
	"freetype_render_target/VerticalLcd":   "Render sub-pixel glyphs for vertical-stripe LCD panels.",
	"DEFAULT":                              "FreeType's default hinting behaviour (no extra flags).",
	"NO_HINTING":                           "Disable hinting: glyph shapes stay true to the font outline.",
	"NO_BITMAP":                            "Ignore embedded bitmap strikes and always render from outlines.",
	"FORCE_AUTOHINT":                       "Use FreeType's auto-hinter even if the font has its own hints.",
	"MONOCHROME":                           "Load glyphs as 1-bit monochrome.",
	"NO_AUTOHINT":                          "Never use the auto-hinter.",
	"NO_SVG":                               "Ignore OpenType-SVG glyphs.",
	"SVG_ONLY":                             "Only render OpenType-SVG glyphs.",
	"freetype_interpreter_version/35":      "Original TrueType bytecode interpreter: classic full hinting.",
	"freetype_interpreter_version/38":      "Infinality interpreter: sub-pixel style hinting.",
	"freetype_interpreter_version/40":      "Current default: ClearType-style, hints vertically only.",
	"display_pixel_geometry/RGB":           "Sub-pixels are ordered red, green, blue from left to right.",
	"display_pixel_geometry/BGR":           "Sub-pixels are ordered blue, green, red from left to right.",
	"allow_square_glyphs_to_overflow_width/WhenFollowedBySpace": "Square glyphs (e.g. icons) may spill into the next cell only if that cell is blank.",
	"allow_square_glyphs_to_overflow_width/Always":              "Square glyphs may always spill into the next cell.",
	"allow_square_glyphs_to_overflow_width/Never":               "Square glyphs are always squeezed into a single cell.",
	"bidi_direction/LeftToRight":                                "Force a left-to-right base direction.",
	"bidi_direction/RightToLeft":                                "Force a right-to-left base direction.",
	"bidi_direction/AutoLeftToRight":                            "Detect the direction per paragraph, falling back to left-to-right.",
	"bidi_direction/AutoRightToLeft":                            "Detect the direction per paragraph, falling back to right-to-left.",
	"bold_brightens_ansi_colors/BrightAndBold":                  "Bold text in ANSI colours 0-7 uses the bright colour (8-15) and a bold font.",
	"bold_brightens_ansi_colors/BrightOnly":                     "Bold text uses the bright colour but stays in the regular weight.",
	"bold_brightens_ansi_colors/No":                             "Bold only changes the font weight; colours are unchanged.",
	"stretch/UltraCondensed":                                    "Narrowest width.",
	"stretch/ExtraCondensed":                                    "Very narrow.",
	"stretch/Condensed":                                         "Narrow.",
	"stretch/SemiCondensed":                                     "Slightly narrow.",
	"stretch/Normal":                                            "Regular width.",
	"stretch/SemiExpanded":                                      "Slightly wide.",
	"stretch/Expanded":                                          "Wide.",
	"stretch/ExtraExpanded":                                     "Very wide.",
	"stretch/UltraExpanded":                                     "Widest.",
	"style/Normal":                                              "Upright (roman) letters.",
	"style/Italic":                                              "The font's true italic design.",
	"style/Oblique":                                             "Slanted upright letters.",
	"intensity/Normal":                                          "Cells drawn at normal intensity.",
	"intensity/Bold":                                            "Cells drawn bold.",
	"intensity/Half":                                            "Cells drawn dim (half intensity).",
	"underline/None":                                            "No underline.",
	"underline/Single":                                          "A single straight line.",
	"underline/Double":                                          "Two straight lines.",
	"underline/Curly":                                           "A wavy line (like spell-check).",
	"underline/Dotted":                                          "A dotted line.",
	"underline/Dashed":                                          "A dashed line.",
	"blink/None":                                                "Not blinking.",
	"blink/Slow":                                                "Blinks slowly.",
	"blink/Rapid":                                               "Blinks rapidly.",

	// ---- window
	"MACOS_FORCE_DISABLE_SHADOW":                   "macOS: never draw the window shadow.",
	"MACOS_FORCE_ENABLE_SHADOW":                    "macOS: always draw the window shadow.",
	"MACOS_FORCE_SQUARE_CORNERS":                   "macOS: square window corners instead of rounded ones.",
	"MACOS_USE_BACKGROUND_COLOR_AS_TITLEBAR_COLOR": "macOS: paint the title bar with the terminal background colour.",
	"TITLE":              "Show a title bar.",
	"RESIZE":             "Allow resizing by dragging the window border.",
	"INTEGRATED_BUTTONS": "Draw the minimise/maximise/close buttons inside the tab bar (needs the fancy tab bar).",
	"integrated_title_button_alignment/Right":   "Window buttons on the right of the tab bar.",
	"integrated_title_button_alignment/Left":    "Window buttons on the left of the tab bar.",
	"integrated_title_button_style/Windows":     "Windows-style minimise, maximise and close buttons.",
	"integrated_title_button_style/Gnome":       "GNOME-style round buttons.",
	"integrated_title_button_style/MacOsNative": "Native macOS traffic-light buttons (macOS only).",
	"win32_system_backdrop/Auto":                "Let Windows pick the backdrop.",
	"win32_system_backdrop/Disable":             "Plain window with no system backdrop.",
	"win32_system_backdrop/Acrylic":             "Blurred, translucent Acrylic material.",
	"win32_system_backdrop/Mica":                "Mica material, subtly tinted by your wallpaper.",
	"win32_system_backdrop/Tabbed":              "Mica Alt: a stronger tinted variant of Mica.",
	"front_end/OpenGL":                          "Render with OpenGL (the default).",
	"front_end/WebGpu":                          "Render with WebGPU (Vulkan, Metal or DX12).",
	"front_end/Software":                        "Render on the CPU: slowest, but works without a GPU.",
	"webgpu_power_preference/LowPower":          "Prefer the integrated GPU to save battery.",
	"webgpu_power_preference/HighPerformance":   "Prefer the discrete GPU for speed.",
	"SetWindowLevel/Normal":                     "Normal window stacking.",
	"SetWindowLevel/AlwaysOnBottom":             "Keep the window below all others.",
	"SetWindowLevel/AlwaysOnTop":                "Keep the window above all others.",

	// ---- cursor
	"SteadyBlock":       "Solid block that doesn't blink.",
	"BlinkingBlock":     "Solid block that blinks.",
	"SteadyUnderline":   "Underscore that doesn't blink.",
	"BlinkingUnderline": "Underscore that blinks.",
	"SteadyBar":         "Thin vertical bar that doesn't blink.",
	"BlinkingBar":       "Thin vertical bar that blinks.",

	// ---- keyboard, mouse, input
	"key_map_preference/Mapped":                              "Match keys by the character they produce in your current layout.",
	"key_map_preference/Physical":                            "Match keys by physical position, independent of layout.",
	"ime_preedit_rendering/Builtin":                          "WezTerm draws the IME's in-progress text itself.",
	"ime_preedit_rendering/System":                           "The system IME draws its in-progress text.",
	"canonicalize_pasted_newlines/None":                      "Paste text unchanged.",
	"canonicalize_pasted_newlines/LineFeed":                  "Convert pasted newlines to LF (\\n).",
	"canonicalize_pasted_newlines/CarriageReturn":            "Convert pasted newlines to CR (\\r), which is what pressing Enter sends.",
	"canonicalize_pasted_newlines/CarriageReturnAndLineFeed": "Convert pasted newlines to CRLF (\\r\\n).",
	"quote_dropped_files/None":                               "Insert the dropped file's path as is.",
	"quote_dropped_files/SpacesOnly":                         "Escape only spaces with a backslash.",
	"quote_dropped_files/Posix":                              "Quote the path for a POSIX shell.",
	"quote_dropped_files/Windows":                            "Quote the path for cmd.exe, only when it needs it.",
	"quote_dropped_files/WindowsAlwaysQuoted":                "Always wrap the path in double quotes (cmd.exe).",
	"ui_key_cap_rendering/UnixLong":                          "Spell out keys the Unix way: Ctrl, Alt, Super.",
	"ui_key_cap_rendering/Emacs":                             "Emacs notation: C-, M-, s-.",
	"ui_key_cap_rendering/AppleSymbols":                      "Apple symbols: control, option, command.",
	"ui_key_cap_rendering/WindowsLong":                       "Spell out keys the Windows way: Ctrl, Alt, Win.",
	"ui_key_cap_rendering/WindowsSymbols":                    "Windows symbols such as the Windows logo.",

	// ---- action arguments
	"ClearScrollback/ScrollbackOnly":        "Erase the scrollback history but keep what is on screen.",
	"ClearScrollback/ScrollbackAndViewport": "Erase the scrollback history and the visible screen.",
	"Clockwise":                             "Rotate panes clockwise.",
	"CounterClockwise":                      "Rotate panes counter-clockwise.",
	"Activate":                              "Focus the chosen pane.",
	"SwapWithActive":                        "Swap the chosen pane with the active pane, then focus the swapped pane.",
	"SwapWithActiveKeepFocus":               "Swap the chosen pane with the active pane, keeping focus where it was.",
	"MoveToNewTab":                          "Move the chosen pane into a new tab.",
	"MoveToNewWindow":                       "Move the chosen pane into a new window.",
	"RecentlyUsed":                          "Characters you picked recently.",
	"SmileysAndEmotion":                     "Smiley and emotion emoji.",
	"PeopleAndBody":                         "People and body-part emoji.",
	"AnimalsAndNature":                      "Animal and nature emoji.",
	"FoodAndDrink":                          "Food and drink emoji.",
	"TravelAndPlaces":                       "Travel and place emoji.",
	"Activities":                            "Activity and sport emoji.",
	"Objects":                               "Object emoji.",
	"Symbols":                               "Symbol emoji.",
	"Flags":                                 "Flag emoji.",
	"NerdFonts":                             "Nerd Font icon glyphs.",
	"UnicodeNames":                          "Search all Unicode characters by name.",
	"ShortCodes":                            "Search emoji by :short-code:.",
	"FUZZY":                                 "Fuzzy-search the list instead of exact matching.",
	"TABS":                                  "Include open tabs.",
	"LAUNCH_MENU_ITEMS":                     "Include your launch_menu entries.",
	"DOMAINS":                               "Include multiplexer domains.",
	"KEY_ASSIGNMENTS":                       "Include key assignments.",
	"WORKSPACES":                            "Include workspaces.",
	"COMMANDS":                              "Include the command palette commands.",
	"kind/Up":                               "The button was released.",
	"kind/Drag":                             "The button is held while the mouse moves.",
	"alt_screen/Any":                        "Match on the normal and the alternate screen.",
	"alt_screen/true":                       "Match only on the alternate screen (vim, less, ...).",
	"alt_screen/false":                      "Match only on the normal screen.",

	"kind/Down": "The button was pressed.",

	// ---- background, gradients, visual bell
	"target/BackgroundColor":   "Flash the terminal background colour.",
	"target/CursorColor":       "Flash the cursor colour.",
	"origin/BorderBox":         "Position the image relative to the window including its border.",
	"origin/PaddingBox":        "Position the image relative to the padded content area.",
	"vertical_align/Top":       "Align the image to the top.",
	"vertical_align/Middle":    "Center the image vertically.",
	"vertical_align/Bottom":    "Align the image to the bottom.",
	"horizontal_align/Left":    "Align the image to the left.",
	"horizontal_align/Center":  "Center the image horizontally.",
	"horizontal_align/Right":   "Align the image to the right.",
	"horizontal/Left":          "Align to the left.",
	"horizontal/Center":        "Center horizontally.",
	"horizontal/Right":         "Align to the right.",
	"vertical/Top":             "Align to the top.",
	"vertical/Center":          "Center vertically.",
	"vertical/Bottom":          "Align to the bottom.",
	"interpolation/Linear":     "Straight blend between colour stops.",
	"interpolation/Basis":      "Smooth B-spline curve that follows, but doesn't pass through, the stops.",
	"interpolation/CatmullRom": "Smooth spline that passes through every stop.",
	"blend/Rgb":                "Blend in gamma-encoded RGB.",
	"blend/LinearRgb":          "Blend in linear RGB: physically accurate mixing.",
	"blend/Hsv":                "Blend hue, saturation and value: passes through the rainbow.",
	"blend/Oklab":              "Blend in the perceptually uniform Oklab space: smooth-looking gradients.",
	"preset/Blues":             "ColorBrewer sequential: light to dark blue.",
	"preset/BrBg":              "ColorBrewer diverging: brown through white to blue-green.",
	"preset/BuGn":              "ColorBrewer sequential: blue to green.",
	"preset/BuPu":              "ColorBrewer sequential: blue to purple.",
	"preset/Cividis":           "Colour-blind friendly: dark blue to yellow.",
	"preset/Cool":              "Cyan to magenta.",
	"preset/CubeHelixDefault":  "Cubehelix: black to white spiralling through colours, prints well in grayscale.",
	"preset/GnBu":              "ColorBrewer sequential: green to blue.",
	"preset/Greens":            "ColorBrewer sequential: light to dark green.",
	"preset/Greys":             "ColorBrewer sequential: white to black.",
	"preset/Inferno":           "Perceptually uniform: black through purple and orange to pale yellow.",
	"preset/Magma":             "Perceptually uniform: black through purple and pink to cream.",
	"preset/OrRd":              "ColorBrewer sequential: orange to red.",
	"preset/Oranges":           "ColorBrewer sequential: light to dark orange.",
	"preset/PiYg":              "ColorBrewer diverging: pink through white to yellow-green.",
	"preset/Plasma":            "Perceptually uniform: deep blue through magenta to yellow.",
	"preset/PrGn":              "ColorBrewer diverging: purple through white to green.",
	"preset/PuBu":              "ColorBrewer sequential: purple to blue.",
	"preset/PuBuGn":            "ColorBrewer sequential: purple through blue to green.",
	"preset/PuOr":              "ColorBrewer diverging: orange through white to purple.",
	"preset/PuRd":              "ColorBrewer sequential: purple to red.",
	"preset/Purples":           "ColorBrewer sequential: light to dark purple.",
	"preset/Rainbow":           "Cycles through the full rainbow.",
	"preset/RdBu":              "ColorBrewer diverging: red through white to blue.",
	"preset/RdGy":              "ColorBrewer diverging: red through white to gray.",
	"preset/RdPu":              "ColorBrewer sequential: red to purple.",
	"preset/RdYlBu":            "ColorBrewer diverging: red, yellow, blue.",
	"preset/RdYlGn":            "ColorBrewer diverging: red, yellow, green.",
	"preset/Reds":              "ColorBrewer sequential: light to dark red.",
	"preset/Sinebow":           "A smooth, cyclic rainbow.",
	"preset/Spectral":          "ColorBrewer diverging: red, yellow, green, blue.",
	"preset/Turbo":             "An improved rainbow: dark blue through green to dark red.",
	"preset/Viridis":           "Perceptually uniform, colour-blind friendly: purple through green to yellow.",
	"preset/Warm":              "Magenta to yellow.",
	"preset/YlGn":              "ColorBrewer sequential: yellow to green.",
	"preset/YlGnBu":            "ColorBrewer sequential: yellow through green to blue.",
	"preset/YlOrBr":            "ColorBrewer sequential: yellow through orange to brown.",
	"preset/YlOrRd":            "ColorBrewer sequential: yellow through orange to red.",

	// ---- ANSI colour names (palette slots 0-15)
	"Black":   "ANSI colour 0.",
	"Maroon":  "ANSI colour 1 (dark red).",
	"Green":   "ANSI colour 2.",
	"Olive":   "ANSI colour 3 (dark yellow).",
	"Navy":    "ANSI colour 4 (dark blue).",
	"Purple":  "ANSI colour 5 (dark magenta).",
	"Teal":    "ANSI colour 6 (dark cyan).",
	"Silver":  "ANSI colour 7 (light gray).",
	"Grey":    "ANSI colour 8 (bright black).",
	"Red":     "ANSI colour 9 (bright red).",
	"Lime":    "ANSI colour 10 (bright green).",
	"Yellow":  "ANSI colour 11 (bright yellow).",
	"Blue":    "ANSI colour 12 (bright blue).",
	"Fuchsia": "ANSI colour 13 (bright magenta).",
	"Aqua":    "ANSI colour 14 (bright cyan).",
	"White":   "ANSI colour 15 (bright white).",
}

// ValueDoc returns the explanation of one choice of the named field, or "".
func ValueDoc(field, value string) string {
	if d, ok := valueDocs[field+"/"+value]; ok {
		return d
	}
	return valueDocs[value]
}
